<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "homework1";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'Computer Science')",
                "INSERT INTO " + schema + ".COMMENT VALUES (NEXT VALUE FOR COMMENT_GEN, 'Skeleton code', 1)",
                "INSERT INTO " + schema + ".COMMENT VALUES (NEXT VALUE FOR COMMENT_GEN, 'for homework1', 1)",
                //"INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'bos123', 'bos')",
              // "INSERT INTO " + schema + ".CUSTOMERS VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'juan.perez@example.com','Juan Pérez')"
                    
                    // Insertando credenciales para los usuarios
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'unodos','Soylamari')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'trescinco','jana_lopz')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN,'tresseis','lector123')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob','sob')",
                "INSERT INTO " + schema + ".CUSTOMERS VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'maria14_lopez@gmail.com', 'Maria Lopez', 'unodos','Soylamari')",
                "INSERT INTO " + schema + ".CUSTOMERS VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'jana98@hotmail.com', 'Jana Fernández','trescinco','jana_lopz')",
                "INSERT INTO " + schema + ".CUSTOMERS VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'susiVic45@gmail.com', 'Susana Vic','tresseis', 'lector123')",
                 "INSERT INTO " + schema + ".CUSTOMERS VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'sob_sob@hotmail.com', 'SOB SOB', 'sob','sob')",
               // "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'Computer Science')",
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'Artificial Intelligence')",
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'Machine Learning')",
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'Future Networks')",
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'Quantum Processors')",
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'Smart Healthcare')",
               // Insertando artículos con contenido completo
"INSERT INTO " + schema + ".ARTICLES VALUES (NEXT VALUE FOR ARTICLE_GEN,'Artificial Intelligence (AI) has seen remarkable progress in recent years. This article highlights key innovations in machine learning, neural networks, and other AI technologies that are transforming industries. These advancements enable better automation, improved decision-making, and significant breakthroughs in areas like natural language processing and computer vision. AI systems are becoming more sophisticated, capable of learning from vast datasets and making predictions with increasing accuracy. The article also explores the growing role of AI in various fields, including healthcare, finance, and transportation, emphasizing how these technologies are reshaping the world around us. While AI presents numerous opportunities, it also raises ethical concerns regarding bias, privacy, and the future of work. With ongoing research and development, AI continues to evolve, promising a future filled with exciting technological possibilities.',1, CURRENT_DATE,'This article discusses key advancements in Artificial Intelligence, focusing on machine learning and neural networks.','A breakthrough in technology', 100, 1)",



"INSERT INTO " + schema + ".ARTICLES VALUES (NEXT VALUE FOR ARTICLE_GEN, 'Generative AI models, such as GANs (Generative Adversarial Networks) and large language models, have become a key focus in artificial intelligence research. These models can generate realistic images, text, and even videos, opening new possibilities in fields like entertainment, design, and marketing. This article explores how generative AI is being applied in creative industries, from automated content creation to virtual reality experiences. Additionally, it addresses the challenges associated with generative models, such as ethical considerations, biases in generated content, and the potential misuse of technology. As generative AI evolves, it holds promise for transforming the way content is created and consumed in the digital era.',1 , CURRENT_DATE,'This article highlights new trends in AI research, especially generative models and their real-world applications.','New AI', 120, 2)",

"INSERT INTO " + schema + ".ARTICLES VALUES (NEXT VALUE FOR ARTICLE_GEN, 'Technological advancements are rapidly changing the landscape of modern society. This article delves into key developments in areas such as cloud computing, edge computing, and artificial intelligence. These innovations are driving digital transformation across industries, from healthcare and finance to retail and education. Cloud computing enables scalable storage and processing, while edge computing improves real-time data processing at the source. The article also discusses emerging trends, such as the Internet of Things (IoT) and smart cities, highlighting how interconnected devices and data-driven systems are reshaping urban living and business operations. While technology offers numerous benefits, it also presents challenges related to cybersecurity, privacy, and the digital divide.',0, CURRENT_DATE,'This article reviews the latest technologies and their impact on society and various industries.','Technology', 130, 3)",


"INSERT INTO " + schema + ".ARTICLES VALUES (NEXT VALUE FOR ARTICLE_GEN, 'The rapid pace of advancements in computer science continues to shape industries globally. This article provides an in-depth look at key innovations, including cloud computing, machine learning, and quantum technologies. From enabling more efficient business processes to enhancing communication and fostering creativity, these technologies are transforming how we live and work. The article also touches on the impact of automation, the rise of smart devices, and the potential for future breakthroughs in quantum computing. As computer science evolves, it brings both opportunities and challenges, such as the need for skilled professionals and the importance of ethical considerations in technology development.', 0, CURRENT_DATE,'This article explores computer science innovations transforming industries worldwide.','The Transformative Power of Computers', 150, 1)",


"INSERT INTO " + schema + ".ARTICLES VALUES (NEXT VALUE FOR ARTICLE_GEN,'Quantum computing is poised to revolutionize the way we process information. This article discusses recent breakthroughs in quantum processors, which are capable of solving complex problems far beyond the reach of classical computers. These advancements have significant implications for cryptography, optimization, and scientific research. Companies and research institutions worldwide are investing heavily in quantum technologies, aiming to achieve quantum supremacy. The article also explores potential real-world applications, such as improving supply chain logistics, accelerating drug discovery, and enhancing machine learning models. Despite its promise, quantum computing still faces challenges related to hardware stability and error correction, but progress continues to be made.',0, CURRENT_DATE,'This article highlights breakthroughs in quantum computing and their potential applications.','Quantum Computing Era', 160, 2)",

"INSERT INTO " + schema + ".ARTICLES VALUES (NEXT VALUE FOR ARTICLE_GEN,'Artificial intelligence is playing an increasingly important role in the healthcare industry. This article focuses on how AI is being used to improve diagnostics, develop personalized treatment plans, and enhance patient care. Machine learning algorithms are capable of analyzing vast datasets, such as medical records and imaging scans, to detect patterns that may be missed by human doctors. Additionally, AI-driven tools are assisting in drug discovery and clinical trials, speeding up the process of bringing new treatments to market. The article also highlights the potential benefits and risks of AI in healthcare, emphasizing the need for regulation, transparency, and collaboration between medical professionals and technologists.', 1, CURRENT_DATE,'This article reviews the role of AI in healthcare, improving diagnostics and personalized medicine.','AI in Healthcare', 115, 3)",
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topic_id) VALUES (1, 1)",
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topic_id) VALUES (2, 3)",
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topic_id) VALUES (3, 2)",
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topic_id) VALUES (4, 3)",
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topic_id) VALUES (5, 5)",
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topic_id) VALUES (6, 6)",
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topic_id) VALUES (6, 2)"
                
                    
               
            };
            try {
    for (String datum : data) {
        if (stmt.executeUpdate(datum) <= 0) {
            out.println("<span class='error'>Error al insertar: " + datum + "</span>");
            return;
        }
        out.println("<pre> -> " + datum + "</pre>");
    }
} catch (SQLException e) {
    out.println("<div class='error'>Error SQL: " + e.getMessage() + "</div>");
}
 
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
